<a href="https://colab.research.google.com/github/isj0/DataAnalysis-Python/blob/main/Types_%26_NA_Values.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import pandas as pd

houses = pd.read_csv("/content/drive/MyDrive/Work/DataAnalysis/data/kc_house_data.csv")
titanic = pd.read_csv("/content/drive/MyDrive/Work/DataAnalysis/data/titanic.csv")
netflix = pd.read_csv("/content/drive/MyDrive/Work/DataAnalysis/data/netflix_titles.csv", sep="|")
btc = pd.read_csv("/content/drive/MyDrive/Work/DataAnalysis/data/coin_Bitcoin.csv")
countries = pd.read_csv("/content/drive/MyDrive/Work/DataAnalysis/data/world-happiness-report-2021.csv", index_col=0)

In [2]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pclass     1309 non-null   int64
 1   survived   1309 non-null   int64
 2   name       1309 non-null   object
 3   sex        1309 non-null   object
 4   age        1309 non-null   object
 5   sibsp      1309 non-null   int64
 6   parch      1309 non-null   int64
 7   ticket     1309 non-null   object
 8   fare       1309 non-null   object
 9   cabin      1309 non-null   object
 10  embarked   1309 non-null   object
 11  boat       1309 non-null   object
 12  body       1309 non-null   object
 13  home.dest  1309 non-null   object
dtypes: int64(4), object(10)
memory usage: 143.3+ KB

In [3]:
titanic["age"].value_counts()

age
?         263
24         47
22         43
21         41
30         40
         ...
66          1
0.6667      1
76          1
67          1
26.5        1
Name: count, Length: 99, dtype: int64

In [4]:
titanic["age"].replace(["?"], [None], inplace=True)

In [5]:
titanic.age.value_counts()

age
24        47
22        43
21        41
30        40
18        39
          ..
0.3333     1
22.5       1
70.5       1
0.6667     1
26.5       1
Name: count, Length: 98, dtype: int64

In [6]:
titanic.age.value_counts(dropna=False)

age
None      263
24         47
22         43
21         41
30         40
         ...
66          1
0.6667      1
76          1
67          1
26.5        1
Name: count, Length: 99, dtype: int64

In [7]:
titanic["age"].astype("float")

0       29.0000
1        0.9167
2        2.0000
3       30.0000
4       25.0000
         ...
1304    14.5000
1305        NaN
1306    26.5000
1307    27.0000
1308    29.0000
Name: age, Length: 1309, dtype: float64

In [8]:
titanic["age_float"] = titanic["age"].astype("float")

In [9]:
titanic["age"] = titanic["age"].astype("float")

In [10]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 15 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pclass     1309 non-null   int64
 1   survived   1309 non-null   int64
 2   name       1309 non-null   object
 3   sex        1309 non-null   object
 4   age        1046 non-null   float64
 5   sibsp      1309 non-null   int64
 6   parch      1309 non-null   int64
 7   ticket     1309 non-null   object
 8   fare       1309 non-null   object
 9   cabin      1309 non-null   object
 10  embarked   1309 non-null   object
 11  boat       1309 non-null   object
 12  body       1309 non-null   object
 13  home.dest  1309 non-null   object
 14  age_float  1046 non-null   float64
dtypes: float64(2), int64(4), object(9)
memory usage: 153.5+ KB

In [11]:
titanic["age"].mean()

29.8811345124283

In [12]:
titanic["sex"].astype("category")

0       female
1         male
2       female
3         male
4       female
         ...
1304    female
1305    female
1306      male
1307      male
1308      male
Name: sex, Length: 1309, dtype: category
Categories (2, object): ['female', 'male']

In [13]:
titanic["sex"] = titanic["sex"].astype("category")

In [14]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 15 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pclass     1309 non-null   int64
 1   survived   1309 non-null   int64
 2   name       1309 non-null   object
 3   sex        1309 non-null   category
 4   age        1046 non-null   float64
 5   sibsp      1309 non-null   int64
 6   parch      1309 non-null   int64
 7   ticket     1309 non-null   object
 8   fare       1309 non-null   object
 9   cabin      1309 non-null   object
 10  embarked   1309 non-null   object
 11  boat       1309 non-null   object
 12  body       1309 non-null   object
 13  home.dest  1309 non-null   object
 14  age_float  1046 non-null   float64
dtypes: category(1), float64(2), int64(4), object(8)
memory usage: 144.7+ KB

In [15]:
titanic["sex"] = "MALE"

In [16]:
titanic["embarked"].value_counts()

embarked
S    914
C    270
Q    123
?      2
Name: count, dtype: int64

In [17]:
titanic["embarked"] = titanic["embarked"].astype("category")

In [18]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 15 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pclass     1309 non-null   int64
 1   survived   1309 non-null   int64
 2   name       1309 non-null   object
 3   sex        1309 non-null   object
 4   age        1046 non-null   float64
 5   sibsp      1309 non-null   int64
 6   parch      1309 non-null   int64
 7   ticket     1309 non-null   object
 8   fare       1309 non-null   object
 9   cabin      1309 non-null   object
 10  embarked   1309 non-null   category
 11  boat       1309 non-null   object
 12  body       1309 non-null   object
 13  home.dest  1309 non-null   object
 14  age_float  1046 non-null   float64
dtypes: category(1), float64(2), int64(4), object(8)
memory usage: 144.8+ KB

In [20]:
titanic["age"].value_counts()

age
?         263
24         47
22         43
21         41
30         40
         ...
66          1
0.6667      1
76          1
67          1
26.5        1
Name: count, Length: 99, dtype: int64

In [21]:
pd.to_numeric(titanic["age"], errors="coerce")

0       29.0000
1        0.9167
2        2.0000
3       30.0000
4       25.0000
         ...
1304    14.5000
1305        NaN
1306    26.5000
1307    27.0000
1308    29.0000
Name: age, Length: 1309, dtype: float64

In [23]:
titanic["age"] = pd.to_numeric(titanic["age"], errors="coerce")

In [24]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pclass     1309 non-null   int64
 1   survived   1309 non-null   int64
 2   name       1309 non-null   object
 3   sex        1309 non-null   object
 4   age        1046 non-null   float64
 5   sibsp      1309 non-null   int64
 6   parch      1309 non-null   int64
 7   ticket     1309 non-null   object
 8   fare       1309 non-null   object
 9   cabin      1309 non-null   object
 10  embarked   1309 non-null   object
 11  boat       1309 non-null   object
 12  body       1309 non-null   object
 13  home.dest  1309 non-null   object
dtypes: float64(1), int64(4), object(9)
memory usage: 143.3+ KB

In [25]:
game = pd.read_csv("/content/drive/MyDrive/Work/DataAnalysis/data/game_stats.csv")

In [26]:
game

       name      league  points  assists  rebounds
0       bob         nba    22.0      5.0      10.0
1    jessie         NaN    10.0      NaN       2.0
2       stu  euroleague     NaN      NaN       NaN
3   jackson         aba     9.0      NaN       2.0
4  timothee         NaN     8.0      NaN       NaN
5     steph         nba    49.0      8.0      10.0
6       NaN         NaN     NaN      NaN       NaN

In [28]:
game.isna()

    name  league  points  assists  rebounds
0  False   False   False    False     False
1  False    True   False     True     False
2  False   False    True     True      True
3  False   False   False     True     False
4  False    True   False     True      True
5  False   False   False    False     False
6   True    True    True     True      True

In [30]:
game[game["league"].isna()]

       name league  points  assists  rebounds
1    jessie    NaN    10.0      NaN       2.0
4  timothee    NaN     8.0      NaN       NaN
6       NaN    NaN     NaN      NaN       NaN

In [32]:
game["assists"].dropna()

0    5.0
5    8.0
Name: assists, dtype: float64

In [33]:
game

       name      league  points  assists  rebounds
0       bob         nba    22.0      5.0      10.0
1    jessie         NaN    10.0      NaN       2.0
2       stu  euroleague     NaN      NaN       NaN
3   jackson         aba     9.0      NaN       2.0
4  timothee         NaN     8.0      NaN       NaN
5     steph         nba    49.0      8.0      10.0
6       NaN         NaN     NaN      NaN       NaN

In [44]:
assists = game["assists"]

In [45]:
assists

0    5.0
1    NaN
2    NaN
3    NaN
4    NaN
5    8.0
6    NaN
Name: assists, dtype: float64

In [46]:
assists.dropna(inplace=True)

In [47]:
assists

0    5.0
5    8.0
Name: assists, dtype: float64

In [48]:
game.dropna()

    name league  points  assists  rebounds
0    bob    nba    22.0      5.0      10.0
5  steph    nba    49.0      8.0      10.0

In [49]:
game

       name      league  points  assists  rebounds
0       bob         nba    22.0      5.0      10.0
1    jessie         NaN    10.0      NaN       2.0
2       stu  euroleague     NaN      NaN       NaN
3   jackson         aba     9.0      NaN       2.0
4  timothee         NaN     8.0      NaN       NaN
5     steph         nba    49.0      8.0      10.0
6       NaN         NaN     NaN      NaN       NaN

In [50]:
game.fillna(0)

       name      league  points  assists  rebounds
0       bob         nba    22.0      5.0      10.0
1    jessie           0    10.0      0.0       2.0
2       stu  euroleague     0.0      0.0       0.0
3   jackson         aba     9.0      0.0       2.0
4  timothee           0     8.0      0.0       0.0
5     steph         nba    49.0      8.0      10.0
6         0           0     0.0      0.0       0.0

In [53]:
game["league"].fillna("amateur", inplace=True)

In [54]:
game

       name      league  points  assists  rebounds
0       bob         nba    22.0      5.0      10.0
1    jessie     amateur    10.0      NaN       2.0
2       stu  euroleague     NaN      NaN       NaN
3   jackson         aba     9.0      NaN       2.0
4  timothee     amateur     8.0      NaN       NaN
5     steph         nba    49.0      8.0      10.0
6       NaN     amateur     NaN      NaN       NaN

In [55]:
game.fillna({"points":0, "assists":"None"})

       name      league  points assists  rebounds
0       bob         nba    22.0     5.0      10.0
1    jessie     amateur    10.0    None       2.0
2       stu  euroleague     0.0    None       NaN
3   jackson         aba     9.0    None       2.0
4  timothee     amateur     8.0    None       NaN
5     steph         nba    49.0     8.0      10.0
6       NaN     amateur     0.0    None       NaN

In [56]:
sales = pd.read_csv("/content/drive/MyDrive/Work/DataAnalysis/data/sales.csv")

In [57]:
sales

   rating  shipping_zip  billing_zip
0     5.0           NaN      81220.0
1     4.5       94931.0      94931.0
2     NaN       92625.0      92625.0
3     4.5       10003.0      10003.0
4     4.0           NaN      92660.0
5     NaN           NaN          NaN
6     NaN       60007.0      60007.0

In [59]:
sales["shipping_zip"].fillna(sales["billing_zip"], inplace=True)

In [60]:
sales

   rating  shipping_zip  billing_zip
0     5.0       81220.0      81220.0
1     4.5       94931.0      94931.0
2     NaN       92625.0      92625.0
3     4.5       10003.0      10003.0
4     4.0       92660.0      92660.0
5     NaN           NaN          NaN
6     NaN       60007.0      60007.0